name: Matrix

on: push

jobs:
  node_version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6,8,10]
      # fail-fast: true
      max-parallel: 2 # limit jobs running in paralell
    runs-on: ${{ matrix.os }}
    steps:
      - name: log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: log version
        run: node -v
      